(defparameter *families*
  '(("code_analyzer" "classic-six.code_analyzer" "classic-six" "analysisFocus" "macro-expansion-audit")
    ("data_processing" "classic-six.data_processing" "classic-six" "dataWindow" "list-stream-reconciliation")
    ("jargon" "classic-six.jargon" "classic-six" "languagePolicy" "common-lisp-glossary")
    ("metrics" "classic-six.metrics" "classic-six" "signalBlend" "latency-error-consing")
    ("network_activity" "classic-six.network_activity" "classic-six" "transportMix" "socket-http-sse")
    ("system_monitoring" "classic-six.system_monitoring" "classic-six" "telemetryScope" "clisp-runtime-host")
    ("agent_workflows" "modern-core.agent_workflows" "modern-core" "coordinationMode" "macro-dispatch-handshake")
    ("platform_engineering" "modern-core.platform_engineering" "modern-core" "platformSurface" "clisp-native-validation-lane")
    ("observability_ai_runtime" "modern-core.observability_ai_runtime" "modern-core" "runtimeSignals" "logs-metrics-provider-boundary")
    ("delivery_preview_ops" "modern-core.delivery_preview_ops" "modern-core" "deliveryGuardrail" "script-preview-checkpoints")
    ("supply_chain_security" "modern-core.supply_chain_security" "modern-core" "supplyChainPosture" "source-script-attestation")
    ("ai_inference_ops" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("evaluation_and_guardrails" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("knowledge_retrieval" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("edge_client_runtime" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("identity_and_trust" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("aibom_provenance" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("agent_boundary_security" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("embedded_agentic_pipeline" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("data_governance_compliance" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("finops_capacity" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("blockchain_protocol_ops" "fallback.security_blockchain" "fallback-security_blockchain" "fallbackFamily" "security_blockchain")
    ("cross_chain_interop" "fallback.security_blockchain" "fallback-security_blockchain" "fallbackFamily" "security_blockchain")
    ("proof_and_sequencer_ops" "fallback.security_blockchain" "fallback-security_blockchain" "fallbackFamily" "security_blockchain")
    ("hybrid_runtime_ops" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("capacity_cost_controller" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("batch_execution_tuner" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("compiler_maintainer" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("interop_adapter_engineer" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("preflight_capacity_planner" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("simulator_performance_engineer" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("fhir_profile_generator" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("smart_launch_oauth" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("bulk_fhir_population_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("hl7v2_feed_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("clinical_workflow_events" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("dicomweb_imaging_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("openehr_semantic_record_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("device_telemetry_clinical" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("emr_vendor_adapter" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("ocpp_chargepoint_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("ocpi_roaming_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("mcp_a2a_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("streaming_bus_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("service_mesh_rpc_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")))

(defun registry-id (value)
  (substitute #\- #\_ value))

(defun normalize-family (value)
  (substitute #\_ #\- (string-downcase (string-trim '(#\Space #\Tab #\Newline #\Return) value))))

(defun find-family (value)
  (let ((normalized (normalize-family value)))
    (find normalized *families* :key #'first :test #'string=)))

(defun fnv1a (value)
  (let ((hash 2166136261))
    (loop for ch across value do
      (setf hash (mod (* (logxor hash (char-code ch)) 16777619) 4294967296)))
    hash))

(defun json-array-strings (items)
  (format nil "[~{\"~A\"~^,~}]" items))

(defun family-json (family firstp)
  (format t "~A{\"id\":\"~A\",\"registryId\":\"~A\",\"rendererKey\":\"~A\",\"tranche\":\"~A\"}"
          (if firstp "" ",") (first family) (registry-id (first family)) (second family) (third family)))

(defun print-registry ()
  (format t "{\"outputFormats\":[\"text\",\"json\"],")
  (format t "\"flags\":[\"list-values\",\"focus-family\",\"output-format\",\"seed\",\"experimental-provider\"],")
  (format t "\"generatorFamilies\":[")
  (loop for family in *families* for firstp = t then nil do (family-json family firstp))
  (format t "],\"classicSix\":~A," (json-array-strings (mapcar #'registry-id (mapcar #'first (subseq *families* 0 6)))))
  (format t "\"modernCore\":~A," (json-array-strings (mapcar #'registry-id (mapcar #'first (subseq *families* 6 11)))))
  (format t "\"fallbackFamilies\":~A," (json-array-strings (mapcar #'registry-id (mapcar #'first (nthcdr 11 *families*)))))
  (format t "\"implementationMode\":\"family-focus-deterministic\"}~%"))

(defun print-payload (family seed output-format)
  (let* ((id (first family))
         (registry (registry-id id))
         (hash (fnv1a (format nil "~A::~A" seed id)))
         (seconds (mod hash 86400))
         (hour (floor seconds 3600))
         (minute (floor (mod seconds 3600) 60))
         (second (mod seconds 60))
         (sequence (+ 1000 (mod hash 9000)))
         (timestamp (format nil "2026-01-01T~2,'0D:~2,'0D:~2,'0DZ" hour minute second)))
    (if (string= output-format "json")
        (format t "{\"eventType\":\"stakeholder.generator.output\",\"sequence\":~D,\"family\":\"~A\",\"message\":\"Deterministic common-lisp tranche for ~A\",\"timestamp\":\"~A\",\"context\":{\"rendererKey\":\"~A\",\"~A\":\"~A\",\"seedFingerprint\":\"~A-~(~X~)\",\"tranche\":\"~A\",\"commonLispProfile\":\"clisp-list-macro-foundation\"},\"generationProvenance\":{\"sourceRepo\":\"common-lisp-stakeholder\",\"baseline\":\"local-small-tranche-family-focus\",\"experimental\":false,\"adapterType\":\"static-list-catalog\",\"promptVersion\":null},\"outputFormat\":\"json\"}~%"
                sequence id id timestamp (second family) (fourth family) (fifth family) registry hash (third family))
        (progn
          (format t "family: ~A~%" id)
          (format t "renderer: ~A~%" (second family))
          (format t "tranche: ~A~%" (third family))
          (format t "sequence: ~D~%" sequence)
          (format t "timestamp: ~A~%" timestamp)
          (format t "message: Deterministic common-lisp tranche for ~A~%" id)))))

(defun fail (message &optional value)
  (if value
      (format *error-output* "~A: ~A~%" message value)
      (format *error-output* "~A~%" message))
  (ext:exit 2))

(defun main ()
  (let ((args ext:*args*)
        (focus-family nil)
        (seed "default-seed")
        (output-format "text")
        (list-values nil))
    (when (and args (string= (first args) "--"))
      (setf args (rest args)))
    (loop while args do
      (let ((arg (pop args)))
        (cond
          ((string= arg "--list-values") (setf list-values t))
          ((string= arg "--focus-family") (unless args (fail "missing value for --focus-family")) (setf focus-family (pop args)))
          ((string= arg "--seed") (unless args (fail "missing value for --seed")) (setf seed (pop args)))
          ((string= arg "--output-format")
           (unless args (fail "missing value for --output-format"))
           (setf output-format (pop args))
           (unless (or (string= output-format "text") (string= output-format "json"))
             (fail "invalid --output-format" output-format)))
          ((string= arg "--experimental-provider")
           (unless args (fail "missing value for --experimental-provider"))
           (fail "experimental provider is not enabled in the deterministic first tranche" (pop args)))
          ((and (>= (length arg) 15) (string= (subseq arg 0 15) "--experimental-"))
           (fail "experimental flags require --experimental-provider"))
          (t (fail "unknown argument" arg)))))
    (when list-values
      (print-registry)
      (ext:exit 0))
    (unless focus-family
      (fail "focus-family is required and must be a known generator family"))
    (let ((family (find-family focus-family)))
      (unless family (fail "invalid --focus-family" focus-family))
      (print-payload family seed output-format))))

(main)
